apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mychart.fullname" . }}
  annotations:
    kube-score/ignore: 'pod-probes,container-ephemeral-storage-request-and-limit' # TODO
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "mychart.fullname" . }}
  serviceName: {{ include "mychart.fullname" . }}-headless
  template:
    metadata:
      labels:
        app: {{ include "mychart.fullname" . }}
        {{- include "mychart.labels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9998"
        prometheus.io/path: "/metrics"
        ad.datadoghq.com/{{ .Chart.Name }}.check_names: |
          ["openmetrics"]
        ad.datadoghq.com/{{ .Chart.Name }}.init_configs: |
          [{}]
        ad.datadoghq.com/{{ .Chart.Name }}.instances: |
          [
            {
              "openmetrics_endpoint": "http://%%host%%:9998/metrics",
              "namespace": "{{ .Release.Namespace }}",
              "metrics": [".*"]
            }
          ]
    spec:
      {{- if .Values.persistentStorage.enabled }}
      volumes:
        - name: {{ include "mychart.fullname" . }}-storage
          persistentVolumeClaim:
            claimName: {{ include "mychart.fullname" . }}
      {{- end }}
      {{ with .Values.image.pullSecret -}}
      imagePullSecrets:
        - name: {{ . }}
      {{ end -}}
      nodeSelector:
        beta.kubernetes.io/arch: {{ .Values.image.arch }}
      {{- if .Values.persistentStorage.enabled }}
      initContainers:
        - name: set-volume-permissions
          image: alpine:3.15
          imagePullPolicy: Always
          command:
            - chown
            - -R
            - 10001:10001
            - /volume
          volumeMounts:
            - name: {{ include "mychart.fullname" . }}-storage
              mountPath: "/volume"
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 64Mi
          securityContext:
            capabilities:
              drop:
                - all
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            runAsUser: 10001
            runAsGroup: 10001
      {{- end }}
      containers:
        - name: app
          image: "{{ .Values.image.image }}:{{ .Values.image.tag | default (print "v" .Chart.AppVersion)}}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          {{- if .Values.persistentStorage.enabled }}
          volumeMounts:
            - name: {{ include "mychart.fullname" . }}-storage
              mountPath: "/volume"
          {{- end }}
          ports:
            - name: api
              containerPort: 8080
              protocol: TCP
            - name: metrics
              containerPort: 9998
              protocol: TCP
          env:
            - name: LOG_FORMAT
              value: json
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['pod-template-hash']
            - name: DD_ENV
              value: {{ .Values.environment }}
            - name: DD_SERVICE
              value: signup-sequencer
            - name: SERVER
              value: http://0.0.0.0:8080
            {{- range $name, $item := .Values.env }}
            - name: {{ $name }}
              {{- if kindIs "map" $item }}
              {{- $item | toYaml | nindent 14 }}
              {{- else }}
              value: {{ $item | quote }}
              {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - all
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            runAsUser: 10001
            runAsGroup: 10001
          livenessProbe:
           httpGet:
             path: /metrics
             scheme: HTTP
             port: 9998
           initialDelaySeconds: 10
           timeoutSeconds: 10
           successThreshold: 1
           failureThreshold: 6
          readinessProbe:
           httpGet:
             path: /metrics
             scheme: HTTP
             port: 9998
           initialDelaySeconds: 10
           timeoutSeconds: 10
           successThreshold: 1
           failureThreshold: 2
