image:
  image: "ghcr.io/worldcoin/signup-sequencer"
  tag: # Defaults to `v` + appVersion
  arch: amd64 # Either amd64 or arm64
  pullSecret:

labels:
  component: # Defaults to name
  partOf: protocol-signup
  createdBy:

environment: prod
replicas: 1
region: "us-east-1"

canary:
  enabled: false

resources:
  requests:
    cpu: 0.1
    memory: 128Mi
  limits:
    cpu: 16.0
    memory: 4Gi

# Env values can be strings (to be prefixed with `value:`) or objects
env:
  STORAGE_FILE: "/volume/commitments.json" # use mounted EBS Volume
  LOG_FILTER: "ethers_providers::provider=debug"
  ETHEREUM_PROVIDER: "${{ secrets.ALCHEMY_POLYGON_MAINNET_RPC_ENDPOINT }}"
  SIGNING_KEY: "${{ secrets.MAINNET_ACCOUNT_PRIVATE_KEY }}"
  SEMAPHORE_ADDRESS: "${{ secrets.MAINNET_SEMAPHORE_CONTRACT_ADDRESS }}"
  WIPE_STORAGE: true
  MAX_LOG_BLOCKS: 10000
  STARTING_BLOCK: 27829300
  PRIORITY_FEE_MULTIPLIER_PERCENTAGE: 200

# Spec ingress policy for the `api` and `metrics` port.
# Values are a list of NetworkPolicyPeer v1 objects, empty means allow all.
ingress:
  host: "signup.crypto.worldcoin.dev"
  api:
  metrics:
  cors: # Enable Traefik Middleware with CORS headers
    enabled: true

persistentStorage:
  enabled: true
  size: 100Gi
  volumeID: aws://us-east-1a/vol-0ad5bd5c5af15e0c8 # example: aws://us-east-1c/vol-aabbcc123
