openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'signup-sequencer'
  license:
    name: MIT
servers:
  - url: http://localhost:8080
paths:
  /metrics:
    servers:
      - url: http://localhost:9998
    get:
      summary: 'Returns Prometheus application metrics'
      responses:
        '200':
          description: 'Sample response: Details about a user by ID'
          content:
            'application/text':
              example: ''
        default:
          description: Unexpected error
  /insertIdentity:
    post:
      summary: 'Queues an insertion of a new identity into the merkle tree'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdentityCommitment'
      responses:
        '200':
          description: 'Identity insert was successfully queued'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InclusionProof'
        '400':
          description: 'Invalid request'
          content:
            application/json:
              schema:
                description: 'A human-readable explanation of the error condition'
                type: 'string'
  /inclusionProof:
    post:
      summary: 'Get Merkle inclusion proof'
      requestBody:
        description: 'details of the identity to get the inclusion proof for'
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/IdentityCommitment'
      responses:
        '200':
          description: 'A Merkle inclusion proof for an already inserted commitment'
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/InclusionProof'
        '400':
          description: 'Invalid request'
          content:
            application/json:
              schema:
                description: 'A human-readable explanation of the error condition'
                type: 'string'
components:
  schemas:
    IdentityCommitment:
      type: object
      properties:
        identityCommitment:
          type: string
          pattern: '^[A-F0-9]{64}$'
      example:
        groupId: 1
        identityCommitment: '0000F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2'
    FieldElement:
      type: string
      pattern: '^0x[a-f0-9]{64}$'
    InclusionProof:
      type: object
      properties:
        status: { $ref: '#/components/schemas/InclusionProofStatus' }
        root: { $ref: '#/components/schemas/FieldElement' }
        proof:
          type: array
          items:
            oneOf:
              - type: object
                properties:
                  Left: { $ref: '#/components/schemas/FieldElement' }
              - type: object
                properties:
                  Right: { $ref: '#/components/schemas/FieldElement' }
    InclusionProofStatus:
      type: string
      enum: [ 'pending', 'mined', 'confirmed' ]
