name: cd

on:
  push:
    branches: [ main ]
  pull_request: # TODO Remove
    branches: [ main ]


jobs:
  image:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/github-script@v5
        id: author-date
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commit_details = await github.rest.git.getCommit({owner: context.repo.owner, repo: context.repo.repo, commit_sha: context.sha});
            return commit_details.data.author.date
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ github.job }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ github.job }}-
      - name: Build
        uses: docker/build-push-action@v2
        with:
          file: order-watcher/Dockerfile
          build-args: |
            COMMIT_SHA=${{ github.sha }}
            COMMIT_DATE=${{ steps.author-date.outputs.result }}
