name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RUST_NIGHTLY: 2021-11-30
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build (release)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        id: rust
        with:
          toolchain: nightly-${{ env.RUST_NIGHTLY }}
          override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: >-
            ${{ runner.os }}
            ${{ steps.rust.outputs.rustc_hash }}
            ${{ github.job }}
            ${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --locked --all-features --all-targets --release

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        id: rust
        with:
          toolchain: nightly-${{ env.RUST_NIGHTLY }}
          override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: >-
            ${{ runner.os }}
            ${{ steps.rust.outputs.rustc_hash }}
            ${{ github.job }}
            ${{ hashFiles('**/Cargo.lock') }}
      - name: Build and run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked --all-features --all-targets

  bench:
    name: Test benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        id: rust
        with:
          toolchain: nightly-${{ env.RUST_NIGHTLY }}
          override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: >-
            ${{ runner.os }}
            ${{ steps.rust.outputs.rustc_hash }}
            ${{ github.job }}
            ${{ hashFiles('**/Cargo.lock') }}
      - name: Build and test benchmarks
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --locked --bench criterion --features bench -- --test

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-${{ env.RUST_NIGHTLY }}
          override: true
          components: rustfmt
      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        id: rust
        with:
          toolchain: nightly-${{ env.RUST_NIGHTLY }}
          override: true
          components: clippy
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: >-
            ${{ runner.os }}
            ${{ steps.rust.outputs.rustc_hash }}
            ${{ github.job }}
            ${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --locked --all-features --all-targets

  codecov:
    # See <https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/source-based-code-coverage.html>
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        id: rust
        with:
          toolchain: nightly-${{ env.RUST_NIGHTLY }}
          components: llvm-tools-preview
          override: true
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: >-
            ${{ runner.os }}
            ${{ steps.rust.outputs.rustc_hash }}
            ${{ github.job }}
            ${{ hashFiles('**/Cargo.lock') }}
      - name: Install rustfilt and cargo-binutils
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cargo install rustfilt cargo-binutils
      - name: Test with coverage
        env:
          RUSTFLAGS: -Zinstrument-coverage
          LLVM_PROFILE_FILE: profile-%m.profraw
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked --all-features --all-targets --no-fail-fast
      - name: Creating coverage report
        env:
          RUSTFLAGS: -Zinstrument-coverage
        run: |
          # Show files
          ls -lah
          # Merge execution traces
          cargo profdata -- merge -sparse $(find . -iname "profile-*.profraw") -o profile.profdata
          # Export to lcov format for codecov
          # NOTE: The inner cargo test command needs to be the same as above
          cargo cov -- export \
            --format=lcov > profile.lcov \
            --instr-profile=profile.profdata \
            $( \
              for file in \
                $( \
                  cargo test --all-features --all-targets --no-run --message-format=json \
                    | jq -r "select(.profile.test == true) | .filenames[]" \
                    | grep -v dSYM - \
                ); \
              do \
                printf "%s %s " -object $file; \
              done \
            )
      - name: Submit to codecov.io
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Optional for public repos
          flags: test
          fail_ci_if_error: true
          verbose: true

  security_audit:
    name: Dependency Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
