name: Test
on:
  pull_request:
  push: 
    branches:
      - main
jobs:
  test:
    name: Coverage
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install rust
        uses: actions-rs/toolchain@v1
      - name: Install cargo-binutils
        run: cargo install cargo-binutils
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install cargo trapaulin
        run: cargo install cargo-tarpaulin
      - name: Generate code coverage
        run: |
          cargo tarpaulin --avoid-cfg-tarpaulin --no-dead-code --follow-exec --engine llvm --verbose --timeout 120 --out Xml
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Optional for public repos
          flags: test
          fail_ci_if_error: true
          verbose: true